import { useMemo, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, type Agrupacion, type Asociado } from '../api'
import { useToast } from '../components/Toast'

type Form = { id?: string; nombre: string; descripcion: string; asociadoIds: string[] }
const EMPTY: Form = { nombre: '', descripcion: '', asociadoIds: [] }
const button = 'rounded border border-stone-300 bg-white px-3 py-1.5 text-sm hover:bg-stone-50 disabled:opacity-50'

const memberId = (value: Agrupacion['asociadoIds'][number]) => typeof value === 'string' ? value : value.id ?? value._id ?? ''

export function GroupsPage() {
  const toast = useToast(); const qc = useQueryClient(); const [editing, setEditing] = useState<Form | null>(null); const [search, setSearch] = useState('')
  const groups = useQuery({ queryKey: ['agrupaciones'], queryFn: () => api.get<Agrupacion[]>('/api/admin/agrupaciones') })
  const associates = useQuery({ queryKey: ['asociados', 'export'], queryFn: () => api.get<Asociado[]>('/api/admin/asociados/export') })
  const save = useMutation({ mutationFn: (form: Form) => form.id ? api.put<Agrupacion>(`/api/admin/agrupaciones/${form.id}`, form) : api.post<Agrupacion>('/api/admin/agrupaciones', form), onSuccess: (_, form) => { toast('success', form.id ? 'Agrupación actualizada' : 'Agrupación creada'); setEditing(null); void qc.invalidateQueries({ queryKey: ['agrupaciones'] }) }, onError: (e) => toast('error', e instanceof Error ? e.message : 'No se pudo guardar') })
  const remove = useMutation({ mutationFn: (id: string) => api.del(`/api/admin/agrupaciones/${id}`), onSuccess: () => { toast('success', 'Agrupación eliminada'); void qc.invalidateQueries({ queryKey: ['agrupaciones'] }) }, onError: (e) => toast('error', e instanceof Error ? e.message : 'No se pudo eliminar') })
  const begin = (group?: Agrupacion) => setEditing(group ? { id: group.id, nombre: group.nombre, descripcion: group.descripcion, asociadoIds: group.asociadoIds.map(memberId).filter(Boolean) } : { ...EMPTY, asociadoIds: [] })
  return <div><div className="mb-5 flex items-center justify-between"><div><h1 className="text-xl font-semibold">Agrupaciones</h1><p className="text-sm text-stone-500">Bloques de socios que participan juntos en un sorteo.</p></div><button onClick={() => begin()} className="rounded bg-emerald-700 px-3 py-1.5 text-sm text-white">+ Nueva agrupación</button></div>
    {groups.isLoading && <p className="py-12 text-center text-stone-500">Cargando…</p>}
    {groups.isError && <p className="rounded bg-red-50 p-3 text-red-700">No se pudieron cargar las agrupaciones.</p>}
    <div className="overflow-hidden rounded-lg border border-stone-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="px-4 py-3">Nombre</th><th className="px-4 py-3">Socios</th><th className="px-4 py-3">Descripción</th><th className="px-4 py-3"></th></tr></thead><tbody>{groups.data?.map((g) => <tr key={g.id} className="border-t border-stone-100"><td className="px-4 py-3 font-medium">{g.nombre}</td><td className="px-4 py-3">{g.asociadoIds.length}</td><td className="max-w-sm truncate px-4 py-3 text-stone-500">{g.descripcion || '—'}</td><td className="px-4 py-3 text-right"><button className={button} onClick={() => begin(g)}>Editar</button> <button className={`${button} text-red-700`} onClick={() => confirm('¿Eliminar esta agrupación?') && remove.mutate(g.id)}>Eliminar</button></td></tr>)}</tbody></table>{groups.data?.length === 0 && <p className="py-12 text-center text-stone-500">No hay agrupaciones.</p>}</div>
    {editing && <GroupDialog value={editing} associates={associates.data ?? []} search={search} setSearch={setSearch} pending={save.isPending} close={() => setEditing(null)} save={(form) => save.mutate(form)} />}
  </div>
}

function GroupDialog({ value, associates, search, setSearch, pending, close, save }: { value: Form; associates: Asociado[]; search: string; setSearch: (v: string) => void; pending: boolean; close: () => void; save: (v: Form) => void }) {
  const [form, setForm] = useState(value)
  const filtered = useMemo(() => { const q = search.toLocaleLowerCase(); return associates.filter((a) => `${a.nombre} ${a.cedula}`.toLocaleLowerCase().includes(q)) }, [associates, search])
  const toggle = (id: string) => setForm((f) => ({ ...f, asociadoIds: f.asociadoIds.includes(id) ? f.asociadoIds.filter((x) => x !== id) : [...f.asociadoIds, id] }))
  const submit = (e: FormEvent) => { e.preventDefault(); if (form.asociadoIds.length < 2) return; save(form) }
  return <div className="fixed inset-0 z-[1000] grid place-items-center bg-black/45 p-4"><form onSubmit={submit} className="w-full max-w-2xl rounded-lg bg-white p-5 shadow-xl"><div className="mb-4 flex justify-between"><h2 className="text-lg font-semibold">{form.id ? 'Editar' : 'Nueva'} agrupación</h2><button type="button" onClick={close}>✕</button></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Nombre *<input required maxLength={200} value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm font-medium">Descripción<textarea maxLength={2000} value={form.descripcion} onChange={(e) => setForm({ ...form, descripcion: e.target.value })} className="mt-1 w-full rounded border px-3 py-2" /></label></div><div className="mt-4"><div className="mb-2 flex items-center justify-between"><strong className="text-sm">Socios ({form.asociadoIds.length}/500)</strong><input type="search" placeholder="Buscar nombre o cédula…" value={search} onChange={(e) => setSearch(e.target.value)} className="rounded border px-3 py-1.5 text-sm" /></div><div className="max-h-64 overflow-auto rounded border">{filtered.map((a) => <label key={a.id} className="flex cursor-pointer items-center gap-3 border-b px-3 py-2 text-sm last:border-0 hover:bg-stone-50"><input type="checkbox" checked={form.asociadoIds.includes(a.id)} disabled={!form.asociadoIds.includes(a.id) && form.asociadoIds.length >= 500} onChange={() => toggle(a.id)} /><span className="flex-1">{a.nombre}</span><span className="text-stone-400">{a.cedula}</span></label>)}</div>{form.asociadoIds.length < 2 && <p className="mt-1 text-xs text-amber-700">Selecciona al menos 2 socios.</p>}</div><div className="mt-5 flex justify-end gap-2"><button type="button" className={button} onClick={close}>Cancelar</button><button disabled={pending || form.asociadoIds.length < 2} className="rounded bg-emerald-700 px-4 py-2 text-sm text-white disabled:opacity-50">{pending ? 'Guardando…' : 'Guardar'}</button></div></form></div>
}
