// Pre-encodes source images into multiple responsive WebP sizes plus a tiny
// blurred LQIP, then writes a manifest the client imports for <picture> srcset.
//
// Source images live in public/. Outputs go to public/img/ and src/data/imageManifest.ts.
import sharp from 'sharp';
import { readdir, mkdir, writeFile, stat } from 'node:fs/promises';
import { join, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SOURCE_DIR = join(ROOT, 'images-src');
const PUBLIC_DIR = join(ROOT, 'public');
const OUT_DIR = join(PUBLIC_DIR, 'img');
const MANIFEST = join(ROOT, 'src', 'data', 'imageManifest.ts');

const WIDTHS = [480, 960, 1440, 1920];
const QUALITY = 78;
const LQIP_WIDTH = 24;

const SOURCES = [
  { file: 'milpa.jpg', directory: SOURCE_DIR },
  { file: 'steps-milpa.jpg', directory: SOURCE_DIR },
  { file: 'IMG_1093.jpeg', directory: ROOT, slug: 'hero-cultivo', widths: [480, 960] },
  { file: 'IMG_1111.jpeg', directory: ROOT, slug: 'hero-recorrido', widths: [480, 960] },
  { file: 'IMG_1122.jpeg', directory: ROOT, slug: 'hero-siembra', widths: [480, 960] },
  { file: 'IMG_1137.jpeg', directory: ROOT, slug: 'hero-camino', widths: [480, 960] },
  { file: 'IMG_1158.jpeg', directory: ROOT, slug: 'hero-territorio' },
];

await mkdir(OUT_DIR, { recursive: true });

const entries = {};

for (const source of SOURCES) {
  const { file, directory } = source;
  const srcPath = join(directory, file);
  try {
    await stat(srcPath);
  } catch {
    console.warn(`[optimize-images] missing ${file}, skipping`);
    continue;
  }

  const slug = source.slug ?? basename(file, extname(file));
  const meta = await sharp(srcPath).metadata();
  const naturalW = meta.width ?? 0;
  const naturalH = meta.height ?? 0;
  const aspect = naturalW && naturalH ? naturalW / naturalH : 16 / 9;

  const variants = [];
  for (const w of source.widths ?? WIDTHS) {
    if (w > naturalW) continue;
    const outName = `${slug}-${w}.webp`;
    const outPath = join(OUT_DIR, outName);
    await sharp(srcPath)
      .autoOrient()
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: QUALITY, effort: 5 })
      .toFile(outPath);
    variants.push({ width: w, src: `/img/${outName}` });
  }

  const lqipBuffer = await sharp(srcPath)
    .autoOrient()
    .resize({ width: LQIP_WIDTH })
    .blur(0.6)
    .webp({ quality: 35 })
    .toBuffer();
  const lqip = `data:image/webp;base64,${lqipBuffer.toString('base64')}`;

  entries[`/${file}`] = {
    slug,
    aspectRatio: aspect,
    naturalWidth: naturalW,
    naturalHeight: naturalH,
    lqip,
    variants,
  };
  console.log(`[optimize-images] ${file} → ${variants.length} variants, lqip=${lqipBuffer.length}b`);
}

const lines = [
  '// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.',
  'export interface ImageVariant { width: number; src: string }',
  'export interface ImageManifestEntry {',
  '  slug: string;',
  '  aspectRatio: number;',
  '  naturalWidth: number;',
  '  naturalHeight: number;',
  '  lqip: string;',
  '  variants: ImageVariant[];',
  '}',
  '',
  `export const imageManifest: Record<string, ImageManifestEntry> = ${JSON.stringify(entries, null, 2)};`,
  '',
];
await writeFile(MANIFEST, lines.join('\n'));

const sizes = await readdir(OUT_DIR);
console.log(`[optimize-images] wrote ${sizes.length} files to public/img/ and manifest at ${MANIFEST}`);
