// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export interface ImageVariant { width: number; src: string }
export interface ImageManifestEntry {
  slug: string;
  aspectRatio: number;
  naturalWidth: number;
  naturalHeight: number;
  lqip: string;
  variants: ImageVariant[];
}

export const imageManifest: Record<string, ImageManifestEntry> = {
  "/milpa.jpg": {
    "slug": "milpa",
    "aspectRatio": 1.8333333333333333,
    "naturalWidth": 5632,
    "naturalHeight": 3072,
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAwCdASoYAA0APwFqrU6rJiQiMAgBYCAJROACSICUgp8lHQAA/uso9un8Y+IlWic0dM7VvA8uza074C0Xr1qU20t1C0I23zswBcsNkeCXPXFp7t4aKEMBvQsimuP9nD8sLdwA",
    "variants": [
      {
        "width": 480,
        "src": "/img/milpa-480.webp"
      },
      {
        "width": 960,
        "src": "/img/milpa-960.webp"
      },
      {
        "width": 1440,
        "src": "/img/milpa-1440.webp"
      },
      {
        "width": 1920,
        "src": "/img/milpa-1920.webp"
      }
    ]
  },
  "/steps-milpa.jpg": {
    "slug": "steps-milpa",
    "aspectRatio": 1.8333333333333333,
    "naturalWidth": 5632,
    "naturalHeight": 3072,
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoYAA0APwFqrU8rJiQiMAgBYCAJZQDE2CFp5SRXjRtFVgD+6tZ+R+/qYJdQsRc15TZtHtrtxavmtBe3MSH+Tin0KG9Z4/T5vqTLehT0zMabi0TBO3NeCIxiuHXgAA==",
    "variants": [
      {
        "width": 480,
        "src": "/img/steps-milpa-480.webp"
      },
      {
        "width": 960,
        "src": "/img/steps-milpa-960.webp"
      },
      {
        "width": 1440,
        "src": "/img/steps-milpa-1440.webp"
      },
      {
        "width": 1920,
        "src": "/img/steps-milpa-1920.webp"
      }
    ]
  }
};
